---
title: "Testing Functions"
format: html
editor: visual
---

```{r}
library(testthat)
library(devtools)
library(remotes)
```

## Write a function

```{r}
# function with single input (data frame)
mean_range <- function(df) {
  col_means <- apply(X = df, MARGIN = 2, FUN = mean, na.rm = TRUE)
  col_mean_max <- max(col_means)
  col_mean_min <- min(col_means)
  return(c(col_mean_min, col_mean_max)) # returns as a vector instead of separate lines
}
```

```{r}
mean_range(mtcars)
```

```{r}
mean_range(faithful)
```

## Write some unit functions that use testthat

```{r}
# testing that every output should always be 2 values in the returned vector
# nothing returned means it passes
expect_length(mean_range(mtcars), 2)
```

```{r}
# could do expect_class and have it check for "numeric" instead of "double"
expect_type(mean_range(mtcars), "double")
```

```{r}
# testing that the first output in the vector to always be <= the second output
expect_true(mean_range(mtcars)[1] <= mean_range(mtcars)[2])
```

```{r}
source(here::here("src", "name_cart.R"))
```

```{r}
name_cart(food = "enchiladas", animal = "hawk")
```

```{r}
source(here::here("src", "cork_oak_growth.R"))
```

```{r}
height_t2(height_t1 = 20, t1 = 4, t2 = 19)
```

## Sourcing Scripts
